version: '3'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb_local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data  # 永続化するデータのファイルパス
    volumes:
      - ./dynamodb_data:/data  # データの永続化
    ports:
      - 8000:8000

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local

  rabbitmq:
    image: rabbitmq:3.8.17-management
    ports:
      - 5672:5672       # RabbitMQ main port
      - 15672:15672     # RabbitMQ management UI port
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser     # Set your desired username
      - RABBITMQ_DEFAULT_PASS=mypassword # Set your desired password
